   version: '3.9'

   services:
     web:
       build: .
       ports:
         - "8000:5000"      
     web2:
       build: .
       ports:
         - "8001:5000"      
     web3:
       build: .
       ports:
         - "8002:5000"      
     redis:
       image: "redis:alpine"
       container_name: redis_container
       volumes:
         - ./redis_data:/data